mixed-port: 32520
mode: rule
ipv6: true
log-level: info
allow-lan: false
find-process-mode: off
unified-delay: true

geodata-mode: true
geo-update-interval: 24
geo-auto-update: true

secret: "190514"
external-controller: 127.0.0.1:9090
external-ui: ui
external-controller-cors:
  allow-origins:
    - '*'

# ==================global config end=====================

tun:
  enable: true
  auto-detect-interface: true
  auto-route: true
  device: utun1024
  dns-hijack:
  - any:53
  stack: system

sniffer:
  enable: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]

dns:
  enable: true
  cache-max-size: 16384
  listen: 127.0.0.1:7853
  ipv6: true
  enhanced-mode: redir-host
  nameserver-policy:
    "geosite:cn,apple": [dhcp://en0, dhcp://en1]
  proxy-server-nameserver: [https://doh.pub/dns-query]
  nameserver: ["1.1.1.1#DNS", "8.8.4.4#DNS", "tcp://8.8.8.8#DNS"]

x-provider: &base_provider
  type: http
  interval: 1800
  proxy: DIRECT
  health-check:
    enable: true
    url: https://cp.cloudflare.com
    interval: 90
    timeout: 3000
    lazy: true
    expected-status: 204

proxy-providers:
  niubi:
    <<: *base_provider
    url: ""
    path: niubi.yaml
    override:
      additional-prefix: "[niubi]"
      ip-version: ipv6-prefer
  linkcube:
    <<: *base_provider
    url: ""
    path: linkcube.yaml
    override:
      additional-prefix: "[linkcube]"
      ip-version: ipv6-prefer

proxy-groups-anchor: &exclude-filter
  exclude-filter: "(?i)expire|traffic|æœé²œ|å¥—é¤|åˆ°æœŸ|çº¿è·¯|è®¢é˜…|æ›´æ–°|æµé‡|å‰©ä½™|å®¢æˆ·ç«¯|å¦‚æžœ|ç½‘ç«™|0.1x|home"

x-proxies: &proxies
  - West
  - Fast
  - é¦™æ¸¯
  - é¦™æ¸¯-æ‰‹åŠ¨
  - å°æ¹¾
  - å°æ¹¾-æ‰‹åŠ¨
  - æ—¥æœ¬
  - æ—¥æœ¬-æ‰‹åŠ¨
  - æ–°åŠ å¡
  - æ–°åŠ å¡-æ‰‹åŠ¨
  - éŸ©å›½
  - éŸ©å›½-æ‰‹åŠ¨
  - ç¾Žå›½
  - ç¾Žå›½-æ‰‹åŠ¨
  - å…¶å®ƒåœ°åŒº
  - å…¨éƒ¨èŠ‚ç‚¹
  - è‡ªåŠ¨é€‰æ‹©
  - DIRECT
  - REJECT
proxy-groups:
  - name: DNS
    type: url-test
    use: [linkcube]
    <<: *exclude-filter
    exclude-type: direct
    tolerance: 30

  - name: Default
    type: select
    proxies: *proxies
      
  - name: Google
    type: select
    proxies: *proxies

  - name: Telegram
    type: select
    proxies: *proxies

  - name: Twitter
    type: select
    proxies: *proxies

  - name: YouTube
    type: select
    proxies: *proxies

  - name: NETFLIX
    type: select
    proxies: *proxies

  - name: Spotify
    type: select
    proxies: *proxies
    
  - name: Github
    type: select
    proxies: *proxies
    
  - name: AI
    type: select
    proxies: *proxies

  - name: Apple
    type: select
    proxies: *proxies
    
  - name: TikTok
    type: select
    proxies: *proxies

  - name: Fast
    type: url-test
    include-all: true
    exclude-type: direct
    <<: *exclude-filter
    filter: "(?i)æ—¥|æ–°|æ¸¯|å°|éŸ©|JP|SG|HK|TW|KP"

  - name: West
    type: url-test
    include-all: true
    exclude-type: direct
    <<: *exclude-filter
    filter: "(?i)æ—¥|æ–°|ç¾Ž|åŠ |å¾·|æ¾³|JP|SG|US|CA|GE|AU"

  - name: ç¾Žå›½
    type: url-test
    include-all: true
    exclude-type: direct
    <<: *exclude-filter
    filter: "(?i)ç¾Ž|us|unitedstates|united states"

  - name: ç¾Žå›½-æ‰‹åŠ¨
    type: select
    include-all: true
    exclude-type: direct
    <<: *exclude-filter
    filter: "(?i)ç¾Ž|us|unitedstates|united states"

  - name: æ–°åŠ å¡
    type: url-test
    include-all: true
    exclude-type: direct
    <<: *exclude-filter
    filter: "(?i)(æ–°|sg|singapore)"

  - name: æ–°åŠ å¡-æ‰‹åŠ¨
    type: select
    include-all: true
    exclude-type: direct
    <<: *exclude-filter
    filter: "(?i)(æ–°|sg|singapore)"

  - name: é¦™æ¸¯
    type: url-test
    include-all: true
    exclude-type: direct
    <<: *exclude-filter
    filter: "(?i)æ¸¯|hk|hongkong|hong kong"

  - name: é¦™æ¸¯-æ‰‹åŠ¨
    type: select
    include-all: true
    exclude-type: direct
    <<: *exclude-filter
    filter: "(?i)æ¸¯|hk|hongkong|hong kong"

  - name: å°æ¹¾
    type: url-test
    include-all: true
    exclude-type: direct
    <<: *exclude-filter
    filter: "(?i)å°|tw|taiwan"

  - name: å°æ¹¾-æ‰‹åŠ¨
    type: select
    include-all: true
    exclude-type: direct
    <<: *exclude-filter
    filter: "(?i)å°|tw|taiwan"

  - name: æ—¥æœ¬
    type: url-test
    include-all: true
    exclude-type: direct
    <<: *exclude-filter
    filter: "(?i)æ—¥|jp|japan"

  - name: æ—¥æœ¬-æ‰‹åŠ¨
    type: select
    include-all: true
    exclude-type: direct
    <<: *exclude-filter
    filter: "(?i)æ—¥|jp|japan"

  - name: éŸ©å›½
    type: url-test
    include-all: true
    exclude-type: direct
    <<: *exclude-filter
    filter: "(?i)éŸ©|kp|korea"

  - name: éŸ©å›½-æ‰‹åŠ¨
    type: select
    include-all: true
    exclude-type: direct
    <<: *exclude-filter
    filter: "(?i)éŸ©|kp|korea"

  - name: å…¶å®ƒåœ°åŒº
    type: select
    include-all: true
    exclude-type: direct
    <<: *exclude-filter
    filter: "(?i)^(?!.*(?:ðŸ‡­ðŸ‡°|ðŸ‡¯ðŸ‡µ|ðŸ‡ºðŸ‡¸|ðŸ‡¸ðŸ‡¬|ðŸ‡¨ðŸ‡³|æ¸¯|hk|hongkong|å°|tw|taiwan|æ—¥|jp|japan|æ–°|sg|singapore|ç¾Ž|us|unitedstates|éŸ©|kp|korea)).*"

  - name: å…¨éƒ¨èŠ‚ç‚¹
    type: select
    include-all: true
    <<: *exclude-filter
    exclude-type: direct

  - name: è‡ªåŠ¨é€‰æ‹©
    type: url-test
    include-all: true
    <<: *exclude-filter
    exclude-type: direct
    tolerance: 30

rules:
  - GEOSITE,category-ai-!cn,AI
  - GEOSITE,google,Google
  - GEOSITE,CN,DIRECT
  - GEOSITE,category-games@cn,DIRECT
  - GEOSITE,github,Github
  - GEOSITE,apple,Apple
  - GEOSITE,youtube,YouTube
  - GEOSITE,tiktok,TikTok
  - GEOSITE,twitter,Twitter
  - GEOSITE,telegram,Telegram
  - GEOSITE,netflix,NETFLIX
  - GEOSITE,spotify,Spotify

  - GEOIP,private,DIRECT,no-resolve
  - GEOIP,CN,DIRECT,no-resolve
  - GEOIP,telegram,Telegram,no-resolve
  - GEOIP,google,Google,no-resolve
  - GEOIP,netflix,NETFLIX,no-resolve
  - GEOIP,twitter,Twitter,no-resolve
  - MATCH,Default
